cai_frontend:
    resource: "@CaiFrontendBundle/Resources/config/routing.yml"
    prefix:   /

cai_web:
    resource: "@CaiWebBundle/Resources/config/routing.yml"
    prefix:   /backend

gulloa_security:
    resource: "@GulloaSecurityBundle/Resources/config/routing.yml"
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
