services:
     cai_web.auxiliar:
         class: Cai\WebBundle\Utils\Auxiliar
         arguments: [ @doctrine.orm.entity_manager]
#    cai_web.example:
#        class: Cai\WebBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
